---

services:
  haproxy:
    container_name: dashboard-haproxy
    image: haproxy:2.2-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - frontend
      #- backend
      - database
    networks:
      - local

  frontend:
    container_name: dashboard-frontend
    build: ./docker/node/
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/home/node/app
    tty: true
    entrypoint: "npm run docker-entrypoint"
    networks:
      - local

  database:
    container_name: dashboard-database
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_DATABASE: local
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge
